spring:
  application:
    name: forecast-api

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB


  datasource:
    url: jdbc:postgresql://localhost:5432/ForecastAPI
    username: forecastadmin
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
