spring:
  application:
    name: forecast-api
  server:
    port: 8080

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

  datasource:
    url: jdbc:postgresql://weather-forecast-weather-forecast.j.aivencloud.com:15703/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_UF7UPO_TDfClxEBE93n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update