spring:
  application:
    name: forecast-api
  server:
    port: 8080

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

  datasource:
    jdbc: h2:file:/forecast-api/data/forecastdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
